#!/bin/sh

# <--------------->
# Ares Load Shell Script 
# Credits:
#          aixxe - aixxe.net (https://aixxe.net/2016/09/shared-library-injection)
# <--------------->

if grep -q libAres.so /proc/$(pidof csgo_linux64)/maps; then
  exit
fi

sudo gdb -n -q -batch \
  -ex "attach $(pidof csgo_linux64)" \
  -ex "set \$dlopen = (void*(*)(char*, int)) dlopen" \
  -ex "call \$dlopen(\"$(pwd)/libAres.so\", 1)" \
  -ex "detach" \
  -ex "quit"
